# Generated by Django 6.0.5 on 2026-06-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userprofile_avatar_letter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
